### ISSUE TITLE
Which NANT version for VS 2010 projects

### ISSUE THREAD

**Issue by savornicesei** [savornicesei/NAnt2#31]
<a href="https://github.com/balmukundkumar"><img src="https://avatars3.githubusercontent.com/u/4035469?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [balmukundkumar](https://github.com/balmukundkumar)**
_Thursday May 16, 2013 at 09:07 GMT_
_Originally opened as https://github.com/nant/nant/issues/97_

----

Which version of Nant to be used to build VS 2010 project?

**Comment by savornicesei** [comment]
<a href="https://github.com/hfrmobile"><img src="https://avatars2.githubusercontent.com/u/2665207?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hfrmobile](https://github.com/hfrmobile)**
_Thursday May 16, 2013 at 09:58 GMT_

----

Depends how your build script look like. I am using NAnt 0.91 for VS2005 (legacy) and for VS2010 (mostly Windows Phone apps) projects.

When using the &lt;csc&gt; task you're highly depended to .NET / VS version etc. but when using &lt;exec&gt; task you may safe lot of time and having less troubles:

e.g.

``` XML
    <target name="build-xap">
        <exec
                program="VPDExpress.exe"
                workingdir="${build.root}/Proj/Hfr.OnlineTVRecorder.Clients.PhoneClient"
                commandline="Hfr.OnlineTVRecorder.Clients.PhoneClient.sln /build Release">
        </exec>
    </target>
```

hth, hfrmobile

**Comment by savornicesei** [comment]
<a href="https://github.com/balmukundkumar"><img src="https://avatars3.githubusercontent.com/u/4035469?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [balmukundkumar](https://github.com/balmukundkumar)**
_Thursday May 16, 2013 at 12:23 GMT_

----

Thank you for the information. I am using 0.92. The problem is when the below target is called then i have the issue with building the vs2010 project .

``` xml
<target name="build-twin" description="Build TWin targets" depends="build-twinserver">
        <mkdir dir="${LogDir}"/> 
        <echo level="Info" message="Calling ${BuildTool} ${SolutionFile} /rebuild ${TWinConfiguration} /out ${BuildLog}"/>
        <exec program="${BuildTool}" verbose = "true">
            <arg line="${SolutionFile} /rebuild ${TWinConfiguration} /out ${BuildLog}"/>
        </exec>
    </target>
```

**Comment by savornicesei** [comment]
<a href="https://github.com/balmukundkumar"><img src="https://avatars3.githubusercontent.com/u/4035469?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [balmukundkumar](https://github.com/balmukundkumar)**
_Thursday May 16, 2013 at 12:26 GMT_

----

Below is the target in the build script. 

``` xml
<target name="build-twin" description="Build TWin targets" depends="build-twinserver">
        <mkdir dir="${LogDir}"/> 
        <echo level="Info" message="Calling ${BuildTool} ${SolutionFile} /rebuild ${TWinConfiguration} /out ${BuildLog}"/>
        <exec program="${BuildTool}" verbose = "true">
            <arg line="${SolutionFile} /rebuild ${TWinConfiguration} /out ${BuildLog}"/>
        </exec>
</target>
```

The issue seen in the log is, projects start to build but do not finish. Only Message we see is 
 -------Rebuild All started: Project: XYZ, Configuration: BuildXYZWithPortalSvc x86 ------
------ Rebuild All started: Project: XY, Configuration: BuildYZWithPortalSvc Win32 ------

This issue is seen when i use Nant. Because In the Visual studio IDE, everything is fine.

**Comment by savornicesei** [comment]
<a href="https://github.com/balmukundkumar"><img src="https://avatars3.githubusercontent.com/u/4035469?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [balmukundkumar](https://github.com/balmukundkumar)**
_Thursday May 16, 2013 at 12:32 GMT_

----

``` xml
<target name ="X" >
 <exec program="{$buildtool}">
<arg line="${solutionfile} /rebuild ${Configuration} / out ${Buildlog}" />
</target>
```

property name "buildtool" has the value = "C:\Program Files\Microsoft Visual Studio 10.0\Common7\IDE\devenv"

Any issue with NAnt for building  VS 2010? Are we missing something here? Please help

**Comment by savornicesei** [comment]
<a href="https://github.com/hfrmobile"><img src="https://avatars2.githubusercontent.com/u/2665207?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hfrmobile](https://github.com/hfrmobile)**
_Thursday May 16, 2013 at 12:40 GMT_

----

You're welcome!

Paths looks correct but you should specify "devenv.exe" to ensure that not "devenv.com" is used.

Which task are you using? "buildtool" is a property of which task? It's like reading in a crystal ball without seeing the whole task fragment you're using ;-)

Are you providing the .csporj, .sln file or what? Are you compiling a .NET code or C++ or ...?

**Comment by savornicesei** [comment]
<a href="https://github.com/dguder"><img src="https://avatars3.githubusercontent.com/u/395019?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dguder](https://github.com/dguder)**
_Thursday May 16, 2013 at 13:16 GMT_

----

Hi, 
basically I think you should use `msbuild.exe` instead of `devenv.exe` if possible.
Then you might take a look at [msbuild task](http://nantcontrib.sourceforge.net/release/latest/help/tasks/msbuild.html) from nantcontrib
Sample:

``` xml
<msbuild project="${solutionfile}" target="Rebuild" verbosity="detailed" > 
    <property name="Configuration" value="${Configuration}"/> 
    <property name="Platform" value="x86"/>
</msbuild>
```

**Comment by savornicesei** [comment]
<a href="https://github.com/balmukundkumar"><img src="https://avatars3.githubusercontent.com/u/4035469?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [balmukundkumar](https://github.com/balmukundkumar)**
_Thursday May 16, 2013 at 13:33 GMT_

----

I am providing solution file(.sln file).
We have C++ and Csharp projects in the solution.
Also we have 1 setup project.
Our client does not want now to move to MSbuild.

For your question - Which task are you using? "buildtool" is a property of which task?
Task is of buildtool property? I did not get. Please clear me.

**Comment by savornicesei** [comment]
<a href="https://github.com/balmukundkumar"><img src="https://avatars3.githubusercontent.com/u/4035469?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [balmukundkumar](https://github.com/balmukundkumar)**
_Thursday May 16, 2013 at 13:36 GMT_

----

``` xml
<?xml version="1.0"?>
<project name="TWin" default="build-twin">
 <property name="SolutionFile" value="C:\TWinVS2010\TWIN\twin.sln"/>
    <property name="BuildLog" value="${LogDir}\devenv.log"/>
 <property name="BuildTool" value="C:\Program Files\Microsoft Visual Studio 10.0\Common7\IDE\devenv"/>

 <target name="build-twin" description="Build TWin targets" depends="build-twinserver">
        <mkdir dir="${LogDir}"/> 
        <echo level="Info" message="Calling ${BuildTool} ${SolutionFile} /rebuild ${TWinConfiguration} /out ${BuildLog}"/>
        <exec program="${BuildTool}" verbose = "true">
            <arg line="${SolutionFile} /rebuild ${TWinConfiguration} /out ${BuildLog}"/>
        </exec>

    </target>

  <target name="build-twinserver" description="Builds TWinServer targets">
        <echo level="Info" message="Calling ${BuildTool} ${TWinServerDir}\TWinServer.sln /rebuild ${TWinServerConfiguration} /out ${BuildLog}"/>
        <exec program="${BuildTool}">
            <arg line="${TWinServerDir}\TWinServer.sln /rebuild ${TWinServerConfiguration} /out ${BuildLog}"/>
        </exec>
    </target>
</project>
```

This is what i have in the script. With this i get the issue.

**Comment by savornicesei** [comment]
<a href="https://github.com/balmukundkumar"><img src="https://avatars3.githubusercontent.com/u/4035469?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [balmukundkumar](https://github.com/balmukundkumar)**
_Thursday May 16, 2013 at 13:44 GMT_

----

``` xml
<?xml version="1.0"?>
<project name="TWin" default="build-twin">
    <description>TWin build file</description>

    <!-- build configurations -->
    <property name="TWinConfiguration" value="BuildTwinWithPortalSvc"/>
    <property name="TWinServerConfiguration" value="release"/>


    <property name="LogDir" value="E:\buildlogs"/>

      <!-- other properties -->
    <property name="SolutionFile" value="C:\TWinVS2010\TWIN\twin.sln"/>
    <property name="BuildLog" value="${LogDir}\devenv.log"/>
    <property name="StateFile" value="*.state"/>
    <property name="ThisFile" value="Twin.build"/>

      <property name="BuildTool" value="C:\Program Files\Microsoft Visual Studio 10.0\Common7\IDE\devenv"/>

    <target name="build-twin" description="Build TWin targets" depends="build-twinserver">
        <mkdir dir="${LogDir}"/> 
        <echo level="Info" message="Calling ${BuildTool} ${SolutionFile} /rebuild ${TWinConfiguration} /out ${BuildLog}"/>
        <exec program="${BuildTool}" verbose = "true">
            <arg line="${SolutionFile} /rebuild ${TWinConfiguration} /out ${BuildLog}"/>
        </exec>

    </target>

    <target name="build-twinserver" description="Builds TWinServer targets">
        <echo level="Info" message="Calling ${BuildTool} ${TWinServerDir}\TWinServer.sln /rebuild ${TWinServerConfiguration} /out ${BuildLog}"/>
        <exec program="${BuildTool}">
            <arg line="${TWinServerDir}\TWinServer.sln /rebuild ${TWinServerConfiguration} /out ${BuildLog}"/>
        </exec>
    </target>
</project>
```

**Comment by savornicesei** [comment]
<a href="https://github.com/balmukundkumar"><img src="https://avatars3.githubusercontent.com/u/4035469?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [balmukundkumar](https://github.com/balmukundkumar)**
_Thursday May 16, 2013 at 13:45 GMT_

----

Any help here is greatly appreciated. Its been long time that we are unable to resolve the issue. 
Should i try with devenv.exe? Any changes in above script is needed? I am buiilding this in Win 7 OS.

**Comment by savornicesei** [comment]
<a href="https://github.com/balmukundkumar"><img src="https://avatars3.githubusercontent.com/u/4035469?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [balmukundkumar](https://github.com/balmukundkumar)**
_Thursday May 16, 2013 at 13:46 GMT_

----

I doubt NAnt is playin role here, since visuall studio IDe runs succesfully, and also from the commandline usign devenv.

**Comment by savornicesei** [comment]
<a href="https://github.com/hfrmobile"><img src="https://avatars2.githubusercontent.com/u/2665207?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hfrmobile](https://github.com/hfrmobile)**
_Thursday May 16, 2013 at 13:56 GMT_

----

dguder said:

> Then you might take a look at msbuild task from nantcontrib

Looks good to me but what are the advantages compared to the `exec` task approach?

balmukundkumar said:

> Our client does not want now to move to MSbuild.

Since you're using VS2010 you're already using MSbuild implicitly.

> Task is of buildtool property? I did not get. Please clear me.

Forget it. I didn't see the XML code before and didn't see that `buildtool` is a NAnt variable.

To put it in short: What is the problem now? Do you get an error message or something that can help us identifying the problem?

What you should try:
1. ensure that devenv.exe is provided
2. run the Command Prompt evaluated (as admin)
3. ensure that the .sln which is used by the NAnt script really compiles entirely

**Comment by savornicesei** [comment]
<a href="https://github.com/dguder"><img src="https://avatars3.githubusercontent.com/u/395019?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dguder](https://github.com/dguder)**
_Thursday May 16, 2013 at 14:56 GMT_

----

@hfrmobile Using `<msbuild>` task is more nant like than using `<exec>` task. But its basically the same. And you only need Framework SDK and not VS IDE installed on build machine (at least if you not compile C++ or use .vdproj). Also nant's [`<solution>`](http://nant.sourceforge.net/release/latest/help/tasks/solution.html) task is able to build VS2010 sln files.

@balmukundkumar 
One point to mention is to add verbosity parameter to devenv command line and remove the `/out` parameter or check your log file.

PS:
Please quote your xml code with ```xml and its corresponding end tag and check this with preview so that we can see your code online.

**Comment by savornicesei** [comment]
<a href="https://github.com/hfrmobile"><img src="https://avatars2.githubusercontent.com/u/2665207?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hfrmobile](https://github.com/hfrmobile)**
_Thursday May 16, 2013 at 15:15 GMT_

----

@dguder Thanks for the hint. In the past I learned that the `solution` does not work for  "special" project types like "setup/msi", "Windows Mobile" (aka smart device project) or "Windows Phone" project files and so I did it always using `exec` in order to not mix different approaches.

Also running **nunit** or **msunit** test when building a project/solution. Of course can use `nunit2` but on a development machine running various versions of VS, Nunit, MSTest etc. it may be complicated. So I just have to set some environment variables (e.g. PATH to specific version of NUnit I need for a specific project) before executing **NAnt**. Of course such situations are only the case when working for different customers on different projects ...

**Comment by savornicesei** [comment]
<a href="https://github.com/balmukundkumar"><img src="https://avatars3.githubusercontent.com/u/4035469?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [balmukundkumar](https://github.com/balmukundkumar)**
_Friday May 17, 2013 at 04:52 GMT_

----

Thank you all for the inputs.
Ok, let me tell the problem again. 

Our build machine (win 7 OS) has CC.net and NAnt to have automed builds for vs 2010. When a build is triggered, build fails( message that appears in the log is given below).

After investigating further, i tried to replicate it without cc.net(To isolate the issue with Nant, not with CC.net.), just by running Nant at the command line. I could very well notice the issue by the method i follwed. 

Till here Clear? Now see the steps i follwed to run sigle target that builds my project.

When i execute one of the target "build-twin" from the commandline using Nant, the build fails.
When i see the log gnenrated by /out , this is what i have(as below). The issue seen in the log is, projects start to build but do not finish. Only Message we see is .
-------Rebuild All started: Project: XYZ, Configuration: BuildXYZWithPortalSvc x86 ------
------ Rebuild All started: Project: XY, Configuration: BuildYZWithPortalSvc Win32 ------
----- Rebuild All started: Project: X, Configuration: BuildYZWithPortalSvc Win32 ------
- ----Rebuild All started: Project: Y, Configuration: BuildYZWithPortalSvc Win32 ------
  ------ Rebuild All started: Project: IsSaBld, Configuration: BuildTWinWithPortalSvc Win32 ------
  ========== Rebuild All: 35 succeeded, 161 failed, 0 skipped ==========
  Project XYZ has started, but immdediatly, another project has started. project xyz has not finished. Similarly all the projects following that. 

Another starage thing i want to tell is : This issue is random. Sometime it is successfull. Maximum times it fails with above message.Help me here.

Ok another important point on why not use MSBUILD task is, we have one setup project. MSbuild does not support setup project.

**Comment by savornicesei** [comment]
<a href="https://github.com/balmukundkumar"><img src="https://avatars3.githubusercontent.com/u/4035469?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [balmukundkumar](https://github.com/balmukundkumar)**
_Friday May 17, 2013 at 05:36 GMT_

----

Also, how to change the verbosity level in nant script for exec task. I have just made verbose=true. This did not help. I want detailed or diagnostic verbosity.

**Comment by savornicesei** [comment]
<a href="https://github.com/dguder"><img src="https://avatars3.githubusercontent.com/u/395019?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dguder](https://github.com/dguder)**
_Friday May 17, 2013 at 06:51 GMT_

----

@balmukundkumar `verbose=true` is ok for nant exec task, please try to remove `/out` command line switch to get your information to nant. 
@hfrmobile but `msbuild` is working with WiX which I would prefer over deployment projects.

**Comment by savornicesei** [comment]
<a href="https://github.com/balmukundkumar"><img src="https://avatars3.githubusercontent.com/u/4035469?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [balmukundkumar](https://github.com/balmukundkumar)**
_Friday May 17, 2013 at 10:13 GMT_

----

remove /out? what happens if i do that? I will not have the log correct?

**Comment by savornicesei** [comment]
<a href="https://github.com/balmukundkumar"><img src="https://avatars3.githubusercontent.com/u/4035469?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [balmukundkumar](https://github.com/balmukundkumar)**
_Friday May 17, 2013 at 10:14 GMT_

----

Do we have NAnt support team?

**Comment by savornicesei** [comment]
<a href="https://github.com/balmukundkumar"><img src="https://avatars3.githubusercontent.com/u/4035469?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [balmukundkumar](https://github.com/balmukundkumar)**
_Monday May 20, 2013 at 07:08 GMT_

----

I tried with 0.91 version of Nant. No help. problem is still the same.

**Comment by savornicesei** [comment]
<a href="https://github.com/balmukundkumar"><img src="https://avatars3.githubusercontent.com/u/4035469?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [balmukundkumar](https://github.com/balmukundkumar)**
_Monday May 20, 2013 at 07:08 GMT_

----

Treid with devenv.exe. results are the same.

**Comment by savornicesei** [comment]
<a href="https://github.com/balmukundkumar"><img src="https://avatars3.githubusercontent.com/u/4035469?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [balmukundkumar](https://github.com/balmukundkumar)**
_Monday May 20, 2013 at 07:45 GMT_

----

This is what mesage i get on the commandline when Nant is run to build vs 2010 project.

BUILD FAILED
C:\nant-0.92-bin\nant-0.92\bin\Twin.build(61,10):
External Program Failed: C:\Program Files\Microsoft Visual Studio 10.0\Common7\I
DE\devenv.exe (return code was 1)

Total time: 619.7 seconds.

**Comment by savornicesei** [comment]
<a href="https://github.com/hfrmobile"><img src="https://avatars2.githubusercontent.com/u/2665207?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hfrmobile](https://github.com/hfrmobile)**
_Monday May 20, 2013 at 12:17 GMT_

----

> External Program Failed: C:\Program Files\Microsoft Visual Studio 10.0\Common7\I
> DE\devenv.exe (return code was 1)

So the issue/problem is definitively located in your solution/project file(s). Open exactly(!) that solution/project causing that error message! If I should make a guess: One or more files are missing needed to compile the solution.

**Comment by savornicesei** [comment]
<a href="https://github.com/balmukundkumar"><img src="https://avatars3.githubusercontent.com/u/4035469?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [balmukundkumar](https://github.com/balmukundkumar)**
_Monday May 20, 2013 at 13:22 GMT_

----

 Open exactly(!) that solution/project causing that error message  ----- 

Everytime it fails for different project. How to find which project has failed? all i provide is the solution file to build . And we have around 190 projects. And i do not get to see detailed errror message in the log. It is very difficult to find out for what reason the projects are failing .

**Comment by savornicesei** [comment]
<a href="https://github.com/balmukundkumar"><img src="https://avatars3.githubusercontent.com/u/4035469?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [balmukundkumar](https://github.com/balmukundkumar)**
_Monday May 20, 2013 at 13:24 GMT_

----

If there is any specific reason for failure of any project, then that errror has to be seen in the log created. But there is not error message. all i see the message in the log  is 

-----Rebuild all started : Project XYZ -Configuration BuildWithPortalSVC x86---
-----Rebuild all started : Project XY -Configuration BuildWithPortalSVC x86---

**Comment by savornicesei** [comment]
<a href="https://github.com/balmukundkumar"><img src="https://avatars3.githubusercontent.com/u/4035469?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [balmukundkumar](https://github.com/balmukundkumar)**
_Tuesday May 21, 2013 at 05:51 GMT_

----

``` xml
<task name="echo">
      <message level="Info"><![CDATA[Calling C:\Program Files\Microsoft Visual Studio 10.0\Common7\IDE\devenv.exe TWIN\twin.sln /rebuild BuildTwinWithPortalSvc /out buildlogs\devenv.log]]></message>
      <duration>0</duration>
    </task>
    <task name="exec">
      <duration>467298.82080000004</duration>
    </task>
    <duration>468297.22250000003</duration>
  </target>
  <failure>
    <builderror>
      <type>NAnt.Core.BuildException</type>
      <message><![CDATA[External Program Failed: C:\Program Files\Microsoft Visual Studio 10.0\Common7\IDE\devenv.exe (return code was 1)]]></message>
      <location>
        <filename>D:\5.1ForVS2010\Twin.build</filename>
        <linenumber>139</linenumber>
        <columnnumber>10</columnnumber>
      </location>
      <stacktrace><![CDATA[   at NAnt.Core.Tasks.ExternalProgramBase.ExecuteTask()
   at NAnt.Core.Tasks.ExecTask.ExecuteTask()
   at NAnt.Core.Task.Execute()
   at NAnt.Core.Target.Execute()
   at NAnt.Core.Project.Execute(String targetName, Boolean forceDependencies)
   at NAnt.Core.Project.Execute()
   at NAnt.Core.Project.Run()]]></stacktrace>
    </builderror>
  </failure>
  <duration>3012957.8034</duration>
```

**Comment by savornicesei** [comment]
<a href="https://github.com/dguder"><img src="https://avatars3.githubusercontent.com/u/395019?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dguder](https://github.com/dguder)**
_Thursday May 23, 2013 at 09:53 GMT_

----

@balmukundkumar So is everything from devenev you see in nant console also in devenv.log? If so than you can keep `/out` parameter. 
A can think of two things you can try:
- Add `/Log` Parameter to devenv exec call to see internal errors from devenv 
- Add -debug+ command line to nant.exe call (this will create a lot of data. But mayber there will be shown something new)
